### ISSUE TITLE
Issue after starting drive

### ISSUE THREAD

**Issue by KS-HTK** [meatlayer/ets2-mobile-route-advisor#18]
ETS2 Version: 1.45.3.5s
ETS2 Telemetry Server Version: 4.1.2.3
ETS2 Mobile Route Advisor Version: 4.0.4

Issue as reported by Chrome:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'timeScale')
    at Dashboard.internalRender (dashboard-core.js:444:100)
    at Dashboard.internalRender (dashboard-core.js:477:34)
    at Dashboard.internalRender (dashboard-core.js:474:38)
    at Dashboard.internalRender (dashboard-core.js:477:34)
    at Dashboard.animationLoop (dashboard-core.js:339:30)
    at dashboard-core.js:335:38
```

Issue as reported by Firefox:
```
Uncaught TypeError: this.resolveObjectByPath(...) is undefined
    internalRender http://127.0.0.1:25555/scripts/dashboard-core.js:444
    internalRender http://127.0.0.1:25555/scripts/dashboard-core.js:477
    internalRender http://127.0.0.1:25555/scripts/dashboard-core.js:474
    internalRender http://127.0.0.1:25555/scripts/dashboard-core.js:477
    animationLoop http://127.0.0.1:25555/scripts/dashboard-core.js:339
    animationLoop http://127.0.0.1:25555/scripts/dashboard-core.js:335
```

Telemetry at time of error:
https://gist.github.com/KS-HTK/5c3b886e639d6f43ca3264eefad5d91f

**Comment by meatlayer** [comment]
Show folder contents:
C:\Users\%USER%\Documents\Telemetry Server\Html\skins

And:
C:\Users\%USER%\Documents\Telemetry Server\Html\skins\ets2-mobile-route-advisor

**Comment by KS-HTK** [comment]
re-downloaded the linked archive. While it solved my other issue it did not fix this.
As requested the output of `dir` on the mentioned folders:

```
D:\AdditionalSoftware\ets2-telemetry-server-4.1.2.3\Html\skins>dir
 Volume in drive D is games
 Volume Serial Number is 5B8A-F93A

 Directory of D:\AdditionalSoftware\ets2-telemetry-server-4.1.2.3\Html\skins

19/04/2022  18:14    <DIR>          .
16/05/2021  22:32    <DIR>          ..
16/05/2021  22:32    <DIR>          18Speed
16/05/2021  22:32    <DIR>          daf-xf
16/05/2021  22:32    <DIR>          default
16/05/2021  22:32    <DIR>          default-mph
28/10/2022  18:07    <DIR>          ets2-mobile-route-advisor
16/05/2021  22:32    <DIR>          jobmonitor
16/05/2021  22:32    <DIR>          jobmonitor2L
16/05/2021  22:32    <DIR>          jobmonitor2P
16/05/2021  22:32    <DIR>          KW-K100E
16/05/2021  22:32    <DIR>          man-tgx
16/05/2021  22:32    <DIR>          man-tgx-mph
16/05/2021  22:32    <DIR>          mercedes-atego
16/05/2021  22:32    <DIR>          peterbilt579
16/05/2021  22:32    <DIR>          RD-Info
16/05/2021  22:32    <DIR>          Scania
16/05/2021  22:32    <DIR>          t-dashboard-4x
16/05/2021  22:32    <DIR>          template
16/05/2021  22:32    <DIR>          volvo-fh
```

```
D:\AdditionalSoftware\ets2-telemetry-server-4.1.2.3\Html\skins\ets2-mobile-route-advisor>dir
 Volume in drive D is games
 Volume Serial Number is 5B8A-F93A

 Directory of D:\AdditionalSoftware\ets2-telemetry-server-4.1.2.3\Html\skins\ets2-mobile-route-advisor

28/10/2022  18:07    <DIR>          .
19/04/2022  18:14    <DIR>          ..
04/09/2022  13:05                27 .gitignore
04/09/2022  13:05               215 .travis.yml
04/09/2022  13:05             1,354 config.json
04/09/2022  13:05             2,977 CONTRIBUTING.md
28/10/2022  18:07    <DIR>          css
04/09/2022  13:05            13,072 dashboard.css
04/09/2022  13:05            16,291 dashboard.html
04/09/2022  13:05            58,954 dashboard.jpg
04/09/2022  13:05            23,422 dashboard.js
28/10/2022  18:07    <DIR>          docs
28/10/2022  18:07    <DIR>          flags
28/10/2022  18:07    <DIR>          flags-usa
28/10/2022  18:07    <DIR>          img
28/10/2022  18:07    <DIR>          language
04/09/2022  13:05             1,077 LICENSE
27/10/2022  20:21    <DIR>          maps
04/09/2022  13:05             8,833 README.md
28/10/2022  18:07    <DIR>          screenshots
```

**Comment by meatlayer** [comment]
What's the problem now?

**Comment by KS-HTK** [comment]
It solved the issue of showing incorrect version in the skin list. It did not solve this issue…
Chrome still shows 400+ times the `Uncaught TypeError: Cannot set properties of undefined (setting 'timeScale')` error.

**Comment by meatlayer** [comment]
Do you use any mods/add-ons or addons from the steam workshop? If yes, remove and disable them.
Right now I completely uninstalled the telemetry server, downloaded and installed it, put the ets 2-mobile-route-advisor I just downloaded and everything works without errors. In any browsers. 

![ets2](https://user-images.githubusercontent.com/7779729/198856606-0e37756a-5d87-43ff-8b48-ecb99cfdec82.png)

**Comment by KS-HTK** [comment]
Will test that. I use all official add-ons, and very few Steam Workshop mods.
It did work some time back (6 months or so) and the only change I made is game update and added 2 more of the official add-ons.

EDIT:
Did some testing. It works flawless on a new profile, same mods, add-on and game settings.
Reloaded my WorldOfTrucks connected profile and it worked, after a quick travel the issue was back. Will need to test a little bit more. This is getting really annoying as loading times are long.

**Comment by meatlayer** [comment]
I assume that perhaps any of the mods can affect the operation of the telemetry server, because the work of ets2-mobile-route-advisor mainly relies on the operation of the telemetry server. And, if any mod broken the operation of the telemetry server, then, accordingly, the ets2-mobile-route-advisor skin stops working. 
And here I am unlikely to be able to influence it in any way, because [current telemetry server is a separate fork](https://github.com/PauloTNCunha/TelemetryServer4 ) project from an [older version of the telemetry server](https://github.com/Funbit/ets2-telemetry-server).

As one of the possible options, I would try to do the following. If you repeat errors in the work of ets2-mobile-route-advisor, check whether other skins from the list in the dashboard of the telemetry server are working. And if not one of the skins does not work out correctly,  collect all the information on telemetry json, create description of the problem and try to create an "Issue" on https://github.com/PauloTNCunha/TelemetryServer4

Perhaps the author of the fork of the telemetry server will be able to help in any way. The main thing is to describe to him in as much detail as possible exactly how the error is reproduced, specifying the entire list of mods used.

If you don't have time for all this. I can advise you to use this project https://github.com/JAGFx/ets2-dashboard-skin it's more modern, and maybe there won't be any problems when using mods.

**Comment by KS-HTK** [comment]
Ok, thank you for the help anyway. I reported it here, since I thought it was not so much influenced by mods. As the skin has been working for years for me. And I did not add any new mods lately.
That is also why I added the Telemetry json. Maybe i will try building a mock api server to test that specific json. The reported acceleration values seem a little of.
But I currently have little time.

I knew about the situation with the Telemetry Server. I don't enjoy the default skins as much, as I like having the Map, so I did not test them, but I will try that.

Thank you for the link to the other dashboard skin, i will test that the next time i get around to playing.

I'll leave this issue open for now. Will update it if I figure anything out.

**Comment by antoniozurlo50-svg** [comment]
Dear Meatlayer,
Sorry if I wasn't clear, I'll send you two screenshots to show you what happens. If you take the new Iveco S-way truck, whatever tank you customize—whether it's 480 liters or 710 liters, or the double one (480+710 liters)—the capacity in the telemetry always shows zero.

<img width="416" height="263" alt="Image" src="https://github.com/user-attachments/assets/1a19c21d-e2ae-4ee1-bb5a-17e2d02f6822" />

<img width="363" height="203" alt="Image" src="https://github.com/user-attachments/assets/34c25247-0644-4ac0-91e4-bed3cc280023" />

**Comment by antoniozurlo50-svg** [comment]
so the fuel indication for this truck doesn't even appear on your route advisor

<img width="469" height="395" alt="Image" src="https://github.com/user-attachments/assets/f1ef1dbc-76d5-4f9a-94d6-c0ca2cd72e71" />

<img width="929" height="902" alt="Image" src="https://github.com/user-attachments/assets/6c65dcec-89c5-413b-932c-4e44278bd80a" />
